name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install CUnit & build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential pkg-config \
          libcunit1 libcunit1-dev

    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: run-test
      run: ./test-sparsexml
